name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push subtree to gh-pages
        run: |
          git subtree push --prefix site origin gh-pages
